export const movies = [
  {
    genre: "action",
    title: "Action",
    info: [
      {
        id: 1,
        name: "The Avengers",
        img: "theAvengers.webp",
        des: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
        trailer: "https://www.youtube.com/embed/eOrNdBpGMv8",
        directName: "Joss Whedon",
        Topcase: [
          "Robert Downey Jr.",
          "Chris Evans",
          "Mark Ruffalo",
          "Chris Hemsworth",
        ],
      },
      {
        id: 2,
        name: "Avengers: Age of Ultron",
        img: "avengersAgeofUltron.webp",
        des: "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
        trailer: "https://www.youtube.com/embed/tmeOjFno6Do",
        directName: "Joss Whedon",
        Topcase: [
          "Robert Downey Jr.",
          "Chris Evans",
          "Mark Ruffalo",
          "Chris Hemsworth",
        ],
      },
      {
        id: 3,
        name: "Avengers: Infinity War",
        img: "avengersInfinityWar.webp",
        des: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
        trailer: "https://www.youtube.com/embed/g5_w5XrC7Ts",
        directName: "Anthony Russo",
        Topcase: [
          "Robert Downey Jr.",
          "Chris Evans",
          "Mark Ruffalo",
          "Chris Hemsworth",
        ],
      },
      {
        id: 4,
        name: "Avengers: Endgame",
        img: "avengersEndgame.webp",
        des: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        trailer: "https://www.youtube.com/embed/8ugaeA-nMTc",
        directName: "Anthony Russo",
        Topcase: [
          "Robert Downey Jr.",
          "Chris Evans",
          "Mark Ruffalo",
          "Chris Hemsworth",
        ],
      },
    ],
  },
  {
    genre: "fantasy",
    title: "Fantasy",
    info: [
      {
        id: 1,
        name: "Harry Potter and the Philosopher's Stone",
        img: "harryPotterAndThePhilosophersStone.webp",
        des: "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.",
        trailer: "https://www.youtube.com/embed/VyHV0BRtdxo",
        directName: "Chris Columbus",
        Topcase: [
          "Daniel Radcliffe",
          "Rupert Grint",
          "Emma Watson",
          "Tom Felton",
        ],
      },
      {
        id: 2,
        name: "Harry Potter and the Chamber of Secrets",
        img: "harryPotterAndTheChamberOfSecrets.webp",
        des: "An ancient prophecy seems to be coming true when a mysterious presence begins stalking the corridors of a school of magic and leaving its victims paralyzed.",
        trailer: "https://www.youtube.com/embed/jBltxS8HfQ4",
        directName: "Chris Columbus",
        Topcase: [
          "Daniel Radcliffe",
          "Rupert Grint",
          "Emma Watson",
          "Tom Felton",
        ],
      },
      {
        id: 3,
        name: "Harry Potter and the Prisoner of Azkaban",
        img: "harryPotterAndThePrisonerOfAzkaban.webp",
        des: "Harry Potter, Ron and Hermione return to Hogwarts School of Witchcraft and Wizardry for their third year of study, where they delve into the mystery surrounding an escaped prisoner who poses a dangerous threat to the young wizard.",
        trailer: "https://www.youtube.com/embed/mlADTRAWcD4",
        directName: "Alfonso Cuarón",
        Topcase: [
          "Daniel Radcliffe",
          "Rupert Grint",
          "Emma Watson",
          "Tom Felton",
        ],
      },
      {
        id: 4,
        name: "Harry Potter and the Goblet of Fire",
        img: "harryPotterAndTheGobletOfFire.webp",
        des: "Harry Potter finds himself competing in a hazardous tournament between rival schools of magic, but he is distracted by recurring nightmares.",
        trailer: "https://www.youtube.com/embed/XkfKuJckaW4",
        directName: "Mike Newell",
        Topcase: [
          "Daniel Radcliffe",
          "Rupert Grint",
          "Emma Watson",
          "Tom Felton",
        ],
      },
      {
        id: 5,
        name: "Harry Potter and the Order of the Phoenix",
        img: "harryPotterAndTheOrderOfThePhoenix.webp",
        des: "With their warning about Lord Voldemort's return scoffed at, Harry and Dumbledore are targeted by the Wizard authorities as an authoritarian bureaucrat slowly seizes power at Hogwarts.",
        trailer: "https://www.youtube.com/embed/y6ZW7KXaXYk",
        directName: "David Yates",
        Topcase: [
          "Daniel Radcliffe",
          "Rupert Grint",
          "Emma Watson",
          "Tom Felton",
        ],
      },
      {
        id: 6,
        name: "Harry Potter and the Half-Blood Prince",
        img: "harryPotterandTheHalfBloodPrince.webp",
        des: "As Harry Potter begins his sixth year at Hogwarts, he discovers an old book marked as 'the property of the Half-Blood Prince and begins to learn more about Lord Voldemort's dark past.",
        trailer: "https://www.youtube.com/embed/tAiy66Xrsz4",
        directName: "David Yates",
        Topcase: [
          "Daniel Radcliffe",
          "Rupert Grint",
          "Emma Watson",
          "Tom Felton",
        ],
      },
      {
        id: 7,
        name: "Harry Potter and the Deathly Hallows – Part 1",
        img: "harryPotterAndTheDeathlyHallowsPart1.webp",
        des: "As Harry, Ron and Hermione race against time and evil to destroy the Horcruxes, they uncover the existence of the three most powerful objects in the wizarding world: the Deathly Hallows.",
        trailer: "https://www.youtube.com/embed/MxqsmsA8y5k",
        directName: "David Yates",
        Topcase: [
          "Daniel Radcliffe",
          "Rupert Grint",
          "Emma Watson",
          "Tom Felton",
        ],
      },
      {
        id: 8,
        name: "Harry Potter and the Deathly Hallows – Part 2",
        img: "harryPotterAndTheDeathlyHallowsPart2.webp",
        des: "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.",
        trailer: "https://www.youtube.com/embed/5NYt1qirBWg",
        directName: "David Yates",
        Topcase: [
          "Daniel Radcliffe",
          "Rupert Grint",
          "Emma Watson",
          "Tom Felton",
        ],
      },
    ],
  },
];
